### ISSUE TITLE
account page: search through blocks for transactions dynamically

### ISSUE THREAD

**Issue by SjonHortensius** [Alethio/ethereum-lite-explorer#47]
currently the `/account/0x` page is pretty empty - it might be nice to search through recent blocks for transactions to/from this address? This could be done dynamically by iterating blocks while the page is open, starting at the most recent block.

Alternatively the new graphql interface in geth could be used to do this a bit more efficiently, see https://gist.github.com/karalabe/bb68b43e48a630baf73f9862521fe45c

**Comment by use-strict** [comment]
We're in the process of releasing a plugin which displays the transactions for a given account. It uses as data source a new open-source lite pipeline that we developed, offering similar functionality to what the full explorer on `aleth.io` does. This means you will be able to install that together with the lite explorer to have the needed information displayed.

**Comment by use-strict** [comment]
You can already try it now, by running the latest Docker image with the `config.memento.json` preset or you can build it from source. Step by step install instructions can be found [here](https://github.com/Alethio/ethereum-lite-explorer/blob/master/README.md) and [here](https://github.com/Alethio/ethereum-lite-explorer/blob/master/README.md#show-the-transactions-per-account-in-account-page).

You will also need to install [Memento](https://github.com/Alethio/memento), which is the data source for this explorer plugin.
