### ISSUE TITLE
Getting Exited with code 3

### ISSUE THREAD

**Issue by ramvi** [Alethio/ethereum-lite-explorer#52]
What does code 3 mean? How do I troubleshoot this?

**Comment by use-strict** [comment]
Can you add some context to this? Are you running the explorer from the docker image or building from source? What is the command that causes this exit code? Can you post the full output?

**Comment by ramvi** [comment]
* Are you running the explorer from the docker image or building from source? `From source`
* What is the command that causes this exit code? `npm start`
* Full output: I have console logged a couple of the variables in the failing file: https://pastebin.com/r596BmdW

**Comment by use-strict** [comment]
The server starts successfully, but the error occurs when trying to open the default browser. We use an npm package called `opn`, which calls `xdg-open` and fails with exit code 3 (in their docs it's described as "A required tool could not be found."). 

As an easy workaround, you can edit the `dev/index.ts` file and remove the offending line: https://github.com/Alethio/ethereum-lite-explorer/blob/master/dev/index.ts#L33

You can then navigate manually to the explorer localhost:port URL.
