### ISSUE TITLE
Can I add plugin in the Docker container?

### ISSUE THREAD

**Issue by NeverKnowsTomorrow** [Alethio/ethereum-lite-explorer#59]
I have run a ethereum-lite-explorer container, and I want to add some plugins or functions as the README file said.

I use `docker exec -it CONTAINER_ID/bin/sh` to enter the container, and modified the `/app/config.json` according to the README file, and save it. Then I restarted the container but it doesn't work, no new plugins can be found in the ethereum-lite-explorer page.

I also try to copy  the modified `/app/config.json` to /usr/share/nginx/html/, and restart container, it also doesn't work.

I added the "Show the network name" plugin and "Link to a custom deployment of EthStats" (I have started EthStats by docker ) plugin.  None of them can be used. 

Need your help, thanks!

This is my ethereum-lite-explorer container that has been installed plugins:
![1](https://user-images.githubusercontent.com/36879844/69473499-d891cc80-0def-11ea-91f5-bd4b1e186411.jpg)

**Comment by use-strict** [comment]
If you are trying to alter the config file directly inside the container, that won't work as the config won't be persisted when the container is restarted. That's how Docker works.

The correct way is to mount that file from the host file system as specified in the readme. Refer to the last example [here](https://github.com/Alethio/ethereum-lite-explorer#running-in-docker)

Please keep in mind that doing this will also disable the APP_NODE_URL ENV variable from being automatically inserted in the config.json file and you will have to fill it in yourself, under the "nodeUrl" key.

**Comment by use-strict** [comment]
Also make sure you have the latest image locally with: `docker pull alethio/ethereum-lite-explorer`

**Comment by NeverKnowsTomorrow** [comment]
> Also make sure you have the latest image locally with: `docker pull alethio/ethereum-lite-explorer`

Thanks for your help!
