### ISSUE TITLE
Latest DockerHub image not updated?

### ISSUE THREAD

**Issue by gperezalba** [Alethio/ethereum-lite-explorer#60]
Hi,

I've just runned a lite-explorer with memento in a local PoA with Parity. Everything is ok but I can find some differences between my explorer and the https://explorer.aleth.io/. 
When related with Tokens in aleth.io explorer if I search for a tx_hash I can see a summary with "Token Transfers" and "Input data" with the events, but in my blockexplorer I can see just raw log entries... Also when searching for an account the summary is different... I don't know if there's something else I have to configure or if the latest image in Docker hub isn't the same as the one running in aleth.io.

Thanks in advance

Guillermo

**Comment by use-strict** [comment]
Hi, there are indeed some differences between Memento and the explorer behind `https://explorer.aleth.io`. For the latter we use a custom data pipeline, that adds some abstractions and more advanced processing. Memento on the other hand is a more portable version of that pipeline, which is easy to install, at the cost of removing some of those aggregations. We'll continue to improve it to bring in more advanced functionality, but at the moment we can't provide that out-of-the-box. It would require a custom solution.

**Comment by gperezalba** [comment]
Ok I understand... I'll try by myself.

Anyway, good job guys! Thanks

**Comment by deantheiceman** [comment]
Is there any timeline or is there a way we can get involved?
